name: Notificacion a ntfy.sh

on:
  push:
    branches:
      - main  

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  

    - name: Ejecutar Hola Mundo en C#
      run: |
        dotnet new console -o MyApp -n HelloWorldApp --force
        cp HelloWorld.cs MyApp/
        cd MyApp
        dotnet run

    - name: Enviar notificación a ntfy.sh
      run: |
        curl -d "Se ha subido código a main en GitHub Actions!" https://ntfy.sh/devops-itla
